lsmod:
  clrs: 
    - green
    - uncolored
    - blue
    - uncolored
    - yellow
    - magenta
  regex: !ruby/regexp '/^(\w+)(\s+)(\d+)(\s+)(\d+)(.+)/'

whereis:
  clrs: 
    - yellow
    - bold
  regex: !ruby/regexp '/^(.+): (.+)/'

id:
  clrs: 
    - green
    - yellow
  regex: !ruby/regexp '/^(\w+=)(\d+)/'

tail_tork_logs:
  -
    results:
      clrs: 
        - magenta
      regex: !ruby/regexp '/^(Finished.*)/'
    stats:
      clrs: 
        - white
        - white
        - green
        - green
        - yellow
        - yellow
        - red
        - red
        - blue
        - blue
      regex: !ruby/regexp '/(\d+)( tests, )(\d+)( assertions, )(\d+)( failures, )(\d+)( errors, )(\d+)( skips)/'
