lsmod:
  regex: !ruby/regexp
    /^(?<green>\w+)(?<uncolored>\s+)(?<blue>\d+)(?<uncolored>\s+)(?<yellow>\d+)(?<red>.+)/

id:
  clrs: 
  regex: !ruby/regexp 
    /(?<green>\w+=)(?<yellow>\d+)/

tail_tork_logs:
  -
    results:
      regex: !ruby/regexp 
        /^(?<underscore>Finished.*)/
    error:
      regex: !ruby/regexp 
        /(?<red>.+(Error|Failure):)/
    expected:
      regex: !ruby/regexp 
        /(?<blue>--- expected)/
    expected-string:
      regex: !ruby/regexp 
        /(?<blue>-\".+)/
    actual:
      regex: !ruby/regexp 
        /(?<red>\++ actual)/
    actual-string:
      regex: !ruby/regexp 
        /(?<red>\+\".+)/
    at:
      regex: !ruby/regexp 
        /(?<on_yellow>@.+)/
    stats:
      regex: !ruby/regexp 
        /(?<white>\d+ tests, )(?<green>\d+ assertions, )(?<magenta>\d+ failures, )(?<red>\d+ errors, )(?<yellow>\d+ skips)/
